#https://cloud.google.com/build/docs/deploying-builds/deploy-firebase
steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git config -f .gitmodules submodule."src/common".url https://source.developers.google.com/p/rocketsidekick/r/github_thzero_rocket_sidekick-common
      git submodule init
      git submodule update --remote
      echo "one up..."
      ls -a ../
      echo "current..."
      ls -a
      echo "src..."
      ls -a ./src
      echo "src/common..."
      ls -a ./src/common
      echo "recursive"
      ls -R
  # Firebase
#   - name: 'gcr.io/cloud-builders/git'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       echo "one up..."
#       ls -a ../
#       echo "current..."
#       ls -a
#       echo "src..."
#       ls -a ./src
#       echo "src/common..."
#       ls -a ./src/common
#   - name: 'docker:stable'
#     args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.' ]
#   - name: 'node:lts'
#     entrypoint: 'npm'
#     args: ['install', '-g', 'firebase-tools']
  # Install
#   - name: 'gcr.io/cloud-builders/git'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       echo "one up..."
#       ls -a ../
#       echo "current..."
#       ls -a
#       echo "src..."
#       ls -a ./src
#       echo "src/common..."
#       ls -a ./src/common
  #- name: 'gcr.io/cloud-builders/npm:current'
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['install']
  # Test
  #- name: 'gcr.io/cloud-builders/npm:current'
  #- name: 'node:lts'
  # entrypoint: 'npm'
  #  args: ['run', 'test:unit']
  # Build
#   - name: 'gcr.io/cloud-builders/git'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       echo "one up..."
#       ls -a ../
#       echo "current..."
#       ls -a
#       echo "src..."
#       ls -a ./src
#       echo "src/common..."
#       ls -a ./src/common
  #- name: 'gcr.io/cloud-builders/npm:current'
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - '_CONFIG=$_CONFIG'
#   - name: 'docker:latest'
#     args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.' ]
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=gcr.io/$PROJECT_ID/firebase
    - --cache=true
  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    #args: [ 'deploy', '--project', '$PROJECT_ID', '--token', '$_FIREBASE_TOKEN' ]
    args: [ 'deploy', '--project', '$PROJECT_ID' ]
